name: Build & Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branchs
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run 
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build
        run: CI=false npm run build
      - name: Deploy to firebase
        run: |
          sudo npm install -g firebase-tools
          firebase deploy --token ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LUMANU_GH_TRACKER  }}